import Link from "next/link";
import {
  Zap,
  Dumbbell,
  UtensilsCrossed,
  Brain,
  TrendingUp,
  ShoppingCart,
  ScanLine,
} from "lucide-react";
import { GradientButton } from "@/components/react-bits/gradient-button";
import { AnimatedCard } from "@/components/react-bits/animated-card";
import { StaggeredText } from "@/components/react-bits/staggered-text";
import { AnimatedList } from "@/components/react-bits/animated-list";

const features = [
  {
    icon: Brain,
    title: "AI-Powered Plans",
    description:
      "Get personalized workout and meal plans generated by AI, tailored to your goals and preferences.",
  },
  {
    icon: Dumbbell,
    title: "Workout Tracking",
    description:
      "Log every set and rep with an intuitive interface. Track progressive overload automatically.",
  },
  {
    icon: UtensilsCrossed,
    title: "Meal Plans & Tracking",
    description:
      "Complete meal plans with macros, ingredients, and prep instructions. Log meals with one tap.",
  },
  {
    icon: TrendingUp,
    title: "Progress Tracking",
    description:
      "Track weight, progress photos, and trends. Watch your transformation unfold.",
  },
  {
    icon: ShoppingCart,
    title: "Smart Grocery Lists",
    description:
      "Auto-generated grocery lists from your meal plan. Check off items as you shop.",
  },
  {
    icon: ScanLine,
    title: "Menu Scanner",
    description:
      "Snap a photo of any restaurant menu and get instant health-scored recommendations.",
  },
];

export default function LandingPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <header className="flex h-16 items-center justify-between px-6 border-b">
        <div className="flex items-center gap-2">
          <Zap className="h-6 w-6 text-primary" />
          <span className="text-xl font-bold">CutPilot</span>
        </div>
        <div className="flex items-center gap-3">
          <Link href="/login" className="inline-flex items-center justify-center rounded-lg px-2.5 h-8 text-sm font-medium hover:bg-muted hover:text-foreground transition-all">
            Log in
          </Link>
          <GradientButton asChild gradient="primary">
            <Link href="/signup" className="inline-flex items-center justify-center px-2.5 h-8 text-sm font-medium">
              Get Started
            </Link>
          </GradientButton>
        </div>
      </header>

      <main className="flex-1">
        <section className="relative overflow-hidden py-24 md:py-32">
          <div className="mx-auto max-w-4xl px-6 text-center">
            <div className="inline-flex items-center gap-2 rounded-full border px-4 py-1.5 text-sm text-muted-foreground mb-6">
              <Zap className="h-3.5 w-3.5 text-primary" />
              AI-Powered Fitness & Nutrition
            </div>
            <h1 className="text-4xl font-bold tracking-tight md:text-6xl">
              <StaggeredText text="Your cut, " as="span" />
              <StaggeredText text="executed." as="span" className="text-primary" delay={300} />
            </h1>
            <p className="mt-6 text-lg text-muted-foreground max-w-2xl mx-auto">
              CutPilot generates personalized workout and meal plans, tracks
              every rep and calorie, and coaches you in real-time with
              contextual AI — all in one premium app.
            </p>
            <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4">
              <GradientButton asChild gradient="rainbow" size="lg">
                <Link href="/signup" className="inline-flex items-center justify-center px-6 h-10 text-sm font-medium">
                  Start Your Cut Free
                </Link>
              </GradientButton>
              <Link href="/login" className="inline-flex items-center justify-center rounded-lg border border-border bg-background px-2.5 h-9 text-sm font-medium hover:bg-muted transition-all">
                I have an account
              </Link>
            </div>
          </div>
        </section>

        <section className="border-t py-20">
          <div className="mx-auto max-w-6xl px-6">
            <h2 className="text-center text-2xl font-bold md:text-3xl">
              Everything you need to execute
            </h2>
            <p className="mt-3 text-center text-muted-foreground">
              From AI plan generation to daily tracking — one app, zero guesswork.
            </p>

            <AnimatedList className="mt-14 grid gap-6 sm:grid-cols-2 lg:grid-cols-3" animation="fade" staggerDelay={100}>
              {features.map((feature) => (
                <AnimatedCard
                  key={feature.title}
                  hoverEffect="lift"
                  className="p-6"
                >
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                    <feature.icon className="h-5 w-5 text-primary" />
                  </div>
                  <h3 className="mt-4 font-semibold">{feature.title}</h3>
                  <p className="mt-2 text-sm text-muted-foreground">
                    {feature.description}
                  </p>
                </AnimatedCard>
              ))}
            </AnimatedList>
          </div>
        </section>

        <section className="border-t py-20">
          <div className="mx-auto max-w-2xl px-6 text-center">
            <h2 className="text-2xl font-bold md:text-3xl">
              Ready to transform?
            </h2>
            <p className="mt-3 text-muted-foreground">
              Join CutPilot and let AI handle the planning while you handle the execution.
            </p>
            <GradientButton asChild gradient="primary" size="lg" className="mt-8">
              <Link href="/signup" className="inline-flex items-center justify-center px-6 h-10 text-sm font-medium">
                Get Started Now
              </Link>
            </GradientButton>
          </div>
        </section>
      </main>

      <footer className="border-t py-8">
        <div className="mx-auto max-w-6xl px-6 text-center text-sm text-muted-foreground">
          &copy; {new Date().getFullYear()} CutPilot. All rights reserved.
        </div>
      </footer>
    </div>
  );
}
