import Link from "next/link";
import {
  Zap,
  Dumbbell,
  UtensilsCrossed,
  Brain,
  TrendingUp,
  ShoppingCart,
  ScanLine,
} from "lucide-react";
import LetterSwap from "@/components/react-bits/3d-letter-swap";
import BlurHighlight from "@/components/react-bits/blur-highlight";
import AuroraBlur from "@/components/react-bits/aurora-blur";

const features = [
  {
    icon: Brain,
    title: "AI-Powered Plans",
    description:
      "Personalized workout and meal plans generated by AI, tailored to your goals and preferences.",
  },
  {
    icon: Dumbbell,
    title: "Workout Tracking",
    description:
      "Log every set and rep with an intuitive interface. Track progressive overload automatically.",
  },
  {
    icon: UtensilsCrossed,
    title: "Meal Plans & Tracking",
    description:
      "Complete meal plans with macros, ingredients, and prep instructions. Log meals with one tap.",
  },
  {
    icon: TrendingUp,
    title: "Progress Analytics",
    description:
      "Track weight, progress photos, and trends. Watch your transformation unfold over time.",
  },
  {
    icon: ShoppingCart,
    title: "Smart Grocery Lists",
    description:
      "Auto-generated grocery lists from your meal plan. Check off items as you shop.",
  },
  {
    icon: ScanLine,
    title: "Menu Scanner",
    description:
      "Snap a photo of any restaurant menu and get instant health-scored recommendations.",
  },
];

export default function LandingPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <header className="fixed top-0 z-50 w-full border-b border-border/50 bg-background/80 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6">
          <Link href="/" className="flex items-center gap-2.5">
            <Zap className="h-6 w-6 text-primary" />
            <span className="text-xl font-bold tracking-tight">CutPilot</span>
          </Link>
          <div className="flex items-center gap-3">
            <Link
              href="/login"
              className="inline-flex h-9 items-center rounded-lg px-4 text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
            >
              Log in
            </Link>
            <Link
              href="/signup"
              className="inline-flex h-9 items-center rounded-lg bg-primary px-5 text-sm font-semibold text-primary-foreground shadow-sm transition-all hover:bg-primary/90"
            >
              Get Started
            </Link>
          </div>
        </div>
      </header>

      <main className="flex-1 pt-16">
        {/* ── Hero ── */}
        <section className="relative isolate overflow-hidden py-28 md:py-40">
          <div className="pointer-events-none absolute inset-0 -z-10 opacity-25">
            <AuroraBlur
              width="100%"
              height="100%"
              speed={0.4}
              opacity={0.7}
              brightness={0.9}
              saturation={1.3}
              noiseScale={2.5}
              movementX={0.3}
              movementY={0.1}
            />
          </div>

          <div className="pointer-events-none absolute inset-0 -z-10 bg-gradient-to-b from-background/30 via-background/70 to-background" />

          <div className="mx-auto max-w-4xl px-6 text-center">
            <div className="mb-8 inline-flex items-center gap-2 rounded-full border border-border/60 bg-muted/60 px-4 py-1.5 text-sm text-muted-foreground backdrop-blur-sm">
              <Zap className="h-3.5 w-3.5 text-primary" />
              AI-Powered Fitness &amp; Nutrition
            </div>

            <h1 className="text-5xl font-bold tracking-tight md:text-7xl lg:text-8xl">
              <LetterSwap
                as="span"
                className="inline-flex flex-wrap justify-center"
                flipDirection="top"
                staggerInterval={0.035}
                staggerOrigin="first"
                blur
                blurAmount={5}
                duration={0.55}
              >
                Your cut, executed.
              </LetterSwap>
            </h1>

            <div className="mx-auto mt-8 max-w-2xl text-lg leading-relaxed text-muted-foreground md:text-xl">
              <BlurHighlight
                highlightedBits={[
                  "personalized plans",
                  "every rep and calorie",
                  "contextual AI",
                ]}
                highlightColor="hsl(160, 65%, 40%)"
                blurAmount={8}
                blurDuration={0.7}
                highlightDelay={0.5}
                highlightDuration={0.5}
              >
                CutPilot generates personalized plans, tracks every rep and
                calorie, and coaches you with contextual AI — all in one premium
                app.
              </BlurHighlight>
            </div>

            <div className="mt-12 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <Link
                href="/signup"
                className="inline-flex h-12 items-center rounded-xl bg-primary px-8 text-base font-semibold text-primary-foreground shadow-lg shadow-primary/20 transition-all hover:bg-primary/90 hover:shadow-xl hover:shadow-primary/30 hover:-translate-y-0.5"
              >
                Start Your Cut Free
              </Link>
              <Link
                href="/login"
                className="inline-flex h-12 items-center rounded-xl border border-border bg-background/80 px-8 text-base font-medium text-muted-foreground backdrop-blur-sm transition-all hover:bg-muted hover:text-foreground"
              >
                I have an account
              </Link>
            </div>
          </div>
        </section>

        {/* ── Features ── */}
        <section className="border-t border-border/50 bg-muted/30 py-24 md:py-32">
          <div className="mx-auto max-w-6xl px-6">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
                Everything you need to execute
              </h2>
              <p className="mt-4 text-lg text-muted-foreground">
                From AI plan generation to daily tracking — one app, zero
                guesswork.
              </p>
            </div>

            <div className="mt-16 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
              {features.map((feature) => (
                <div
                  key={feature.title}
                  className="group relative rounded-2xl border border-border/60 bg-card p-6 transition-all duration-300 hover:-translate-y-1 hover:border-primary/25 hover:shadow-xl hover:shadow-primary/[0.04]"
                >
                  <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary transition-colors duration-300 group-hover:bg-primary/15">
                    <feature.icon className="h-5 w-5" />
                  </div>
                  <h3 className="mt-4 text-lg font-semibold">
                    {feature.title}
                  </h3>
                  <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                    {feature.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── Bottom CTA ── */}
        <section className="border-t border-border/50 py-24 md:py-32">
          <div className="mx-auto max-w-2xl px-6 text-center">
            <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
              Ready to transform?
            </h2>
            <p className="mt-4 text-lg text-muted-foreground">
              Join CutPilot and let AI handle the planning while you handle the
              execution.
            </p>
            <div className="mt-10">
              <Link
                href="/signup"
                className="inline-flex h-12 items-center rounded-xl bg-primary px-8 text-base font-semibold text-primary-foreground shadow-lg shadow-primary/20 transition-all hover:bg-primary/90 hover:shadow-xl hover:shadow-primary/30 hover:-translate-y-0.5"
              >
                Get Started Now
              </Link>
            </div>
          </div>
        </section>
      </main>

      <footer className="border-t border-border/50 py-8">
        <div className="mx-auto max-w-6xl px-6 text-center text-sm text-muted-foreground">
          &copy; {new Date().getFullYear()} CutPilot. All rights reserved.
        </div>
      </footer>
    </div>
  );
}
