"use client";

import { useRef } from "react";
import { motion, useInView } from "motion/react";
import {
  Brain,
  Dumbbell,
  UtensilsCrossed,
  TrendingUp,
  ShoppingCart,
  ScanLine,
  Timer,
  Sparkles,
} from "lucide-react";

const features = [
  {
    icon: Brain,
    title: "AI-Powered Plans",
    description:
      "Personalized workout and meal plans generated by AI, tailored to your goals, experience, and preferences.",
    color: "from-violet-500/10 to-violet-500/5",
    iconColor: "text-violet-500",
    iconBg: "bg-violet-500/10",
  },
  {
    icon: Dumbbell,
    title: "Workout Tracking",
    description:
      "Log every set and rep with real-time stopwatch timers. Track progressive overload automatically.",
    color: "from-blue-500/10 to-blue-500/5",
    iconColor: "text-blue-500",
    iconBg: "bg-blue-500/10",
  },
  {
    icon: UtensilsCrossed,
    title: "Meal Plans & Tracking",
    description:
      "Complete meal plans with macros, ingredients, and prep instructions. Log meals with one tap.",
    color: "from-emerald-500/10 to-emerald-500/5",
    iconColor: "text-emerald-500",
    iconBg: "bg-emerald-500/10",
  },
  {
    icon: TrendingUp,
    title: "Progress Analytics",
    description:
      "Track weight, progress photos, and trends. Watch your transformation unfold over time.",
    color: "from-amber-500/10 to-amber-500/5",
    iconColor: "text-amber-500",
    iconBg: "bg-amber-500/10",
  },
  {
    icon: ShoppingCart,
    title: "Smart Grocery Lists",
    description:
      "Auto-generated grocery lists from your meal plan. Organized by category, check items as you shop.",
    color: "from-pink-500/10 to-pink-500/5",
    iconColor: "text-pink-500",
    iconBg: "bg-pink-500/10",
  },
  {
    icon: ScanLine,
    title: "Menu Scanner",
    description:
      "Snap a photo of any restaurant menu and get instant AI health-scored recommendations.",
    color: "from-cyan-500/10 to-cyan-500/5",
    iconColor: "text-cyan-500",
    iconBg: "bg-cyan-500/10",
  },
  {
    icon: Timer,
    title: "Workout Timers",
    description:
      "Built-in stopwatch and rest timers for every workout. Auto-start rest between sets.",
    color: "from-orange-500/10 to-orange-500/5",
    iconColor: "text-orange-500",
    iconBg: "bg-orange-500/10",
  },
  {
    icon: Sparkles,
    title: "AI Coach Assistant",
    description:
      "Your always-available AI fitness co-pilot. Ask about form, nutrition, recovery, and motivation.",
    color: "from-primary/10 to-primary/5",
    iconColor: "text-primary",
    iconBg: "bg-primary/10",
  },
];

export function FeaturesSection() {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, amount: 0.1 });

  return (
    <section className="relative py-24 md:py-32">
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute top-0 right-1/4 h-[500px] w-[500px] rounded-full bg-primary/[0.03] blur-[100px]" />
      </div>

      <div ref={ref} className="relative mx-auto max-w-6xl px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
          className="mx-auto max-w-2xl text-center mb-16"
        >
          <span className="inline-flex items-center gap-1.5 rounded-full bg-primary/5 border border-primary/10 px-3 py-1 text-xs font-medium text-primary mb-4">
            Features
          </span>
          <h2 className="text-3xl font-bold tracking-tight md:text-5xl">
            Everything you need to{" "}
            <span className="bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent">
              execute
            </span>
          </h2>
          <p className="mt-4 text-lg text-muted-foreground">
            From AI plan generation to daily tracking — one app, zero guesswork.
          </p>
        </motion.div>

        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {features.map((feature, i) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 30 }}
              animate={inView ? { opacity: 1, y: 0 } : {}}
              transition={{
                delay: 0.1 + i * 0.06,
                duration: 0.5,
                ease: [0.22, 1, 0.36, 1],
              }}
              className="group relative overflow-hidden rounded-2xl border border-border/40 bg-card/50 backdrop-blur-sm p-6 transition-all duration-500 hover:-translate-y-1 hover:border-primary/20 hover:shadow-xl hover:shadow-primary/[0.05]"
            >
              <div className={`absolute inset-0 bg-gradient-to-br ${feature.color} opacity-0 transition-opacity duration-500 group-hover:opacity-100`} />

              <div className="relative">
                <div className={`flex h-10 w-10 items-center justify-center rounded-xl ${feature.iconBg} transition-transform duration-300 group-hover:scale-110`}>
                  <feature.icon className={`h-5 w-5 ${feature.iconColor}`} />
                </div>
                <h3 className="mt-4 text-base font-semibold">
                  {feature.title}
                </h3>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                  {feature.description}
                </p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
